---
deployment:
  tasks:
    - /bin/cp index.html /home/simpxlow/bingogenerator.alloccasionsprintables.com/index.html
    - /bin/cp styles.css /home/simpxlow/bingogenerator.alloccasionsprintables.com/styles.css
    - /bin/cp app.js /home/simpxlow/bingogenerator.alloccasionsprintables.com/app.js
    - /bin/cp robots.txt /home/simpxlow/bingogenerator.alloccasionsprintables.com/robots.txt
    - /bin/cp .htaccess /home/simpxlow/bingogenerator.alloccasionsprintables.com/.htaccess
